services:
  rocketchat:
    container_name: rocketchat
    image: hibobmaster/rocketchat-arm:6.5.0
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./chat:/home/chat

    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0&directConnection=true"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0&directConnection=true"
      # change chat.example.com to your server's name
      ROOT_URL: https://chat.example.com
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb   
    ports:
      - 127.0.0.1:3002:3000

  mongodb:
    container_name: rocketchat-mongodb
    image: mongo:6
    restart: unless-stopped
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/dump
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-init-replica:
    image: mongo:6
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongosh mongodb/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $$s)"
    depends_on:
      - mongodb