name: Publish rocketchat Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tags to publish'
        required: true
        default: 'latest'

permissions:
  contents: read
  packages: write

jobs:
  push_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image(dockerhub)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./rocketchat/Dockerfile
          platforms: linux/arm64
          push: true
          tags: hibobmaster/rocketchat-arm:latest,hibobmaster/rocketchat-arm:${{ github.event.inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image(ghcr)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./rocketchat/Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/hibobmaster/rocketchat-arm:latest,ghcr.io/hibobmaster/rocketchat-arm:${{ github.event.inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max